services:
  redis:
    image: redis/redis-stack-server
    ports:
      - '6379:6379'
  web:
    depends_on:
      - redis
    image: ghcr.io/caarmen/retro-chat
    ports:
      - '8000:8000'
# Comment out the below if you need to set some variables in
# a .env file (see the README.md)
#    volumes:
#      - ${ENV_FILE_PATH:-${PWD}/.env}:/app/server/.env
