services:
  redis:
    image: redis/redis-stack-server
    ports:
      - '6379:6379'
  web:
    depends_on:
      - redis
    image: ghcr.io/caarmen/retrochat
    ports:
      - '8000:8000'
    volumes:
      - ${ENV_FILE_PATH:-${PWD}/.env}:/app/server/.env
