services:
  redis:
    image: redis/redis-stack
    ports:
      - '6379:6379'
      - '8001:8001'
  web:
    depends_on:
      - redis
    build:
      context: ..
      dockerfile: Dockerfile
      target: retrochat_web_base
    ports:
      - '8000:8000'
    volumes:
      - ${ENV_FILE_PATH:-${PWD}/server/.env}:/app/server/.env
